version: "3"
services:
  server:
    image: lscr.io/linuxserver/homeassistant:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bratislava
    volumes:
      - ./config:/config
    ports:
      - 8123:8123
    restart: unless-stopped
